const title = 'HS Analyzer - Helium hotspot tool for analysis';
const shortName = 'HS-A';
const domain = process.env.DOMAIN || 'node.dev';

const config = {
  title: title,
  shortName: shortName,
  domain: domain,

  buildHash: Math.random().toString(36).substring(2),

  HTMLminify: {
    collapseBooleanAttributes: true,
    collapseInlineTagWhitespace: true,
    collapseWhitespace: true,
    includeAutoGeneratedTags: false,
    minifyCSS: true,
    minifyJS: true,
    minifyURLs: true,
    removeComments: true,
    removeEmptyAttributes: true,
    removeOptionalTags: true,
    removeRedundantAttributes: true,
    removeScriptTypeAttributes: true,
    removeStyleLinkTypeAttributes: true,
    removeTagWhitespace: true
  },

  copyFilesProd: {
    patterns: [
      {
        from: './src/static/root-files',
        to: '../dist/'
      },
      {
        context: './src/static',
        from: '**/*',
        to: '../static/',
        globOptions: {
          ignore: [
            'favicon/**/*',
            'global-styles/**/*',
            'images/**/*',
            'root-files/**/*',
            'video/**/*'
          ]
        }
      }
    ]
  },

  copyFiles: {
    patterns: [
      {
        from: './src/static/root-files',
        to: './'
      },
      {
        context: './src/static',
        from: '**/*',
        to: './',
        globOptions: {
          ignore: [
            'favicon/**/*',
            'global-styles/**/*',
            'images/**/*',
            'root-files/**/*',
            'video/**/*'
          ]
        }
      }
    ]
  },

  src: './src',
  dist: './dist',
  staticTo: './static',
  tmp: './.tmp',

  srcAbsolute: 'src',
  distAbsolute: 'dist',
  tmpAbsolute: '.tmp',

  SCSSLintConfigFile: './.stylelintrc',

  favicon: './src/static/favicon/favicon.png',
  components: './src/components',
  'global-styles': './src/global-styles',
  static: './src/static',
  templates: './src/templates'
};

export default config;
